server.port: 8081

endpoints.sensitive: true
management.security.enabled: false

spring.datasource.url: jdbc:h2:./botContainerDB;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto: update

spring.jackson.date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

# logging.level.org.hibernate.SQL: DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# spring.jpa.properties.hibernate.type: trace
