CREATE TABLE BOT (
  ID BIGINT IDENTITY PRIMARY KEY,
  REVISION BIGINT,
  NAME VARCHAR(256),
  CREATED_BY VARCHAR(256),
  REVISED_BY VARCHAR(256),
  CREATED_DATE TIMESTAMP,
  UPDATED_DATE TIMESTAMP,
  ENABLED BOOLEAN,
  SCRIPT VARCHAR(10485760)
);
